FROM node:22-bookworm-slim AS builder
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY . .

RUN corepack enable pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm build

ARG SITE_URL
ENV SITE_URL=${SITE_URL}

RUN pnpm build

FROM node:22-bookworm-slim AS runner
WORKDIR /app

RUN npm install -g serve@14.2.6

COPY --from=builder /app/dist ./web

RUN chown -R node:node /web
USER node

CMD ["sh", "-c", "exec serve web -l \"tcp://0.0.0.0:${PORT}\""]
