server {
    listen 80;
    listen [::]:80;
    server_name apps.azersoft.nc;

    # HTTP -> HTTPS (conserve le query string)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name apps.azersoft.nc;

    # Certbot / Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/apps.azersoft.nc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/apps.azersoft.nc/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Shopify NC Shipping Rates
    # Secured redirect
    location = /shopify-nc-shipping-rates {
        return 301 https://$host/shopify-nc-shipping-rates/$is_args$args;
    }
    # Secured reverse proxy
    location /shopify-nc-shipping-rates/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
    }

    # Tech Mi Home NC
    ## Wordpress
    ## Secured redirect
    location = /tech-mi-home-nc {
        return 301 https://$host/tech-mi-home-nc/$is_args$args;
    }
    # Secured reverse proxy
    location /tech-mi-home-nc/ {
        proxy_pass http://127.0.0.1:3100;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
    }
    ## PHPMyAdmin
    ### Secured redirect
    location = /admin-tech-mi-home-nc {
        return 301 https://$host/admin-tech-mi-home-nc/$is_args$args;
    }
    ### Secured reverse proxy
    location /admin-tech-mi-home-nc/ {
        proxy_pass http://127.0.0.1:3102;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
    }
}